# Generated by Django 4.1.5 on 2023-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60, verbose_name='name')),
                ('age', models.IntegerField(blank=True, default='', verbose_name='age')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], default='', max_length=60, verbose_name='status')),
                ('mail_id', models.EmailField(blank=True, default='', max_length=60, verbose_name='mail_id')),
                ('image1', models.ImageField(blank=True, default='', upload_to='images/', verbose_name='images')),
                ('image2', models.ImageField(blank=True, default='', upload_to='images/', verbose_name='images')),
            ],
        ),
    ]
